### PR TITLE
Document `__foo` syntax for positional-only args

### PR DESCRIPTION
**Pull request by sixolet**
This resolves https://github.com/python/typing/issues/336

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

Unfortunately our records indicate you have not signed a [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA). For legal reasons we need you to sign this before we can look at your contribution.

Once you have done everything that's needed, please reply here and someone will verify everything is in order.

**Comment by sixolet** [comment]
I have done the necessary!  But only a few minutes ago, maybe systems have not caught up.

**Comment by gvanrossum** [comment]
LGTM, can be merged once the CLA signing has been recorded (I can't recall if there's a manual step somewhere in the process still).

**Comment by brettcannon** [comment]
@gvanrossum There's a manual step where @ejodlowska logs the fact that the CLA was received on bugs.python.org, so you should usually give it a day before checking.

**Pull request merged**
