### PR TITLE
abbreviation -> acronym

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by jamesray1** [comment]
Note that I tried to register again, but I had the same issue where when I clicked on the link to confirm my email, I got the error "Invalid URL scheme in homepage URL". Additionally I also replied to the email (as I did weeks ago).

**Comment by JulienPalard** [comment]
@jamesray1 Can you please give me more information about the failure to register:

- At which step exactly it is failing (registering to bugs.python.org vs signing the CLA)
- Can you forward me (julien at palard dot fr) the email with the invalid link, or if you don't trust me (don't trust anyone on the internet) just the link with the token redacted, so I can inspect what's going wrong at which level?
- Any other information that could help us diagnose the issue.

**Comment by brettcannon** [comment]
The PR is small enough I'm going to merge this regardless, but please do keep working with @JulienPalard , @jamesray1 , to figure out what's going on with your registration.

**Comment by jamesray1** [comment]
@JulienPalard, I forwarded you 2 emails. When I register, after I get the notification that an email has been sent to me for confirmation, I go to check the email, and the link doesn't work, nor does replying to it.

**Comment by JulienPalard** [comment]
For the record, the issue is tracked here: http://psf.upfronthosting.co.za/roundup/meta/issue591 you just have to update your "homepage URL" in your profile with a valid scheme first.

**Pull request merged**
