### PR TITLE
PEP 8102: Update Ee W. Durbin III's name

### PR DESCRIPTION
**Pull request by brainwane**
Per https://twitter.com/EWDurbin/status/1337939281835384834 name change.

Signed-off-by: Sumana Harihareswara <sh@changeset.nyc>

### CODE REVIEW

**Comment by hugovk** [comment]
Do these need updating too?

pep-0458.txt
pep-0588.rst
pep-8001.rst
pep-8100.rst
pep-8101.rst

**Comment by brainwane** [comment]
@hugovk: Good question; I'll defer to @ewdurbin on this of course!

**Comment by ewdurbin** [comment]
I actually wanted to take a closer look at the handling of names in general in the PEP repo and was working on this myself.

Specifically the way last names are decided for crediting.
Screen Shot 2020-12-14 at 10 56 09 AM

**Comment by hugovk** [comment]
https://github.com/python/peps/pull/1386 is a PR to fix that.

**Comment by ewdurbin** [comment]
I opened a more comprehensive PR at #1733

**Pull request closed without merging**
