### PR TITLE
PEP 580: Petr Viktorin as BDFL-Delegate

### PR DESCRIPTION
**Pull request by jdemeyer**
See discussion at https://mail.python.org/pipermail/python-dev/2018-October/155403.html

### CODE REVIEW

**Comment by gvanrossum** [comment]
Given the lack of a BDFL, was this discussed somewhere? A reference would be appropriate (in the PR, not necessarily in the PEP). (Writing this with my PEP-editor hat on.)

**Comment by jdemeyer** [comment]
> Given the lack of a BDFL, was this discussed somewhere? A reference would be appropriate (in the PR, not necessarily in the PEP). (Writing this with my PEP-editor hat on.)

There is ongoing discussion, I added a link to python-dev. If you think of "BDFL Delegate" as "PEP Reviewer" (which is what it is in practice), it shouldn't be a problem that there is no BDFL. I should also note that I did ask Antoine Pitrou, INADA Naoki and Nick Coghlan (in private emails) as "experts" and they all approved of Petr becoming BDFL-Delegate.

**Comment by gvanrossum** [comment]
But the role of BDFL-Delegate is different from a reviewer. Anyone can review a PEP. But a BDFL-Delegate can *accept* a PEP. I think you're jumping the gun here. Petr should do a thorough review without the BDFL-Delegate appointment. Implementation (in a fork) can start when he says it's ready.

**Comment by jdemeyer** [comment]
@gvanrossum: I'm not entirely following what you're trying to say here. Are you saying that it's too early to appoint a BDFL-Delegate because PEP 580 hasn't been sufficiently looked at? Or are you saying that it's impossible to follow the BDFL-Delegate process from PEP 1 because of the governance crisis? Or both?

**Comment by encukou** [comment]
- @ambv, the release manager for 3.8 (closest we have to an authority), considers this premature. 
- `BDFL-Delegate` is probably the wrong term anyway.

I'll close this for now.

**Pull request closed without merging**
