### PR TITLE
PEP 622: fix broken internal link

### PR DESCRIPTION
**Pull request by dmoisset**
The link target was broken in 430718e

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@dmoisset

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by Rosuav** [comment]
I clicked on the link in the current version and it seemed to work. Would it be better to use this as a canonical name?

**Comment by dmoisset** [comment]
You're right. I had tested on the github preview and it ddin't work, but it seems the GH .rst renderer is doing something wrong, and the "official" render loks correct and matches the tag. Sorry about that, closing

**Comment by Rosuav** [comment]
Nothing to apologize for! Thanks for helping to keep things clean and tidy :)

**Comment by gvanrossum** [comment]
What happened is that I already fixed it. Sorry for wasting your time!

**Comment by Rosuav** [comment]
Time machine strikes again! GG :)

**Pull request closed without merging**
