### PR TITLE
PEP 622: minor typo and grammar fixes

### PR DESCRIPTION
**Pull request by obestwalter**
There is really not much to say about it - it's a typo and I fixed it :)

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@obestwalter

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by obestwalter** [comment]
I could have sworn I signed a CLA already, but that was before the move to github I think. Will do it now then.

**Comment by obestwalter** [comment]
I signed the CLA and might fix some more things as I am reading through it in the same PR - hope that is ok. Very intriguing proposal btw.

**Comment by Rosuav** [comment]
It might be that you HAVE signed it, but the bot doesn't know. Check your bugs.python.org profile and see if your GitHub user name is correctly entered.

**Pull request merged**
