### PR TITLE
PEP 0526 -- variable declarations

### PR DESCRIPTION
**Pull request by gvanrossum**
This PR is a work in progress, but we may want to merge it just to reserve the PEP number.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

Unfortunately we couldn't find an account corresponding to your GitHub username at [bugs.python.org](http://bugs.python.org/) (b.p.o). If you don't already have an account at b.p.o, please [create one](http://bugs.python.org/user?@template=register) and make sure to add your GitHub username. If you do already have an account at b.p.o then please go there and under "Your Details" add your GitHub username.

And in case you haven't already, please make sure to sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA); we can't legally look at your contribution until you have signed the CLA.

Once you have done everything that's needed, please reply here and someone will verify everything is in order.

**Comment by phouse512** [comment]
@the-knights-who-say-ni I've updated my account and signed the PSF contributor agreement!

**Comment by brettcannon** [comment]
The PR hasn't received CLA clearance because of the commit from @kirbyfan64 who has (at least) not set his GitHub name on bugs.python.org

**Comment by kirbyfan64** [comment]
I signed it now.

**Comment by brettcannon** [comment]
@kirbyfan64 @phouse512  Thanks to both of you! It usually takes a day for the signed document to end up in the proper hands and get the flag flipped on bugs.python.org. We'll then try the CLA check again then tomorrow or Friday.

**Pull request merged**
