### PR TITLE
PEP 575: Unifying function/method classes

### PR DESCRIPTION
**Pull request by jdemeyer**

### CODE REVIEW

**Comment by Rosuav** [comment]
The next PEP number is 573 - go ahead and claim that number.

**Comment by jdemeyer** [comment]
PEP 573 exists (Module State Access from C Extension Methods), so I guess you mean 574.

**Comment by Rosuav** [comment]
That's what I get for pulling changes and not noticing that git popped an error into the console. 575 is correct. Thanks @jdemeyer and sorry for the misinformation!

**Comment by jdemeyer** [comment]
> go ahead and claim that number.

I'm not entirely sure what you meant with this, but I created `pep-0575.rst` in the repo and updated the header.

**Comment by Rosuav** [comment]
Yep! That's exactly what I meant. Your PEP should be live shortly at https://www.python.org/dev/peps/pep-0575/ and you can post to python-ideas with that URL.

**Pull request merged**
