### PR TITLE
PEP 9999: A metadata format for entry points

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@KOLANICH

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by gvanrossum** [comment]
Where was this previously discussed? If this is a PyPA topic, who from the PyPA is responsible?

**Comment by pfmoore** [comment]
I don't believe it has been discussed at all. @KOLANICH you'd need to start the process with a discussion on the Packaging Discourse and get some level of consensus that the idea is OK before submitting a PR here. Also, you'll need a PEP sponsor to help you with the process.

**Comment by brettcannon** [comment]
Closing due to lack of previous discussion in a public forum (preferably https://discuss.python.org/c/packaging/14) and lack of sponsor. Please see https://www.python.org/dev/peps/pep-0001/ for details on the overall process and do note that packaging PEPs have their own specific set of potential sponsors.

**Comment by KOLANICH** [comment]
OK, if we cannot discuss it here, I have created a gist where we can discuss it: https://gist.github.com/KOLANICH/d4684de5da08b72f94e85dc99801f089

**Pull request closed without merging**
