### PR TITLE
PEP 544: Specify usage of modules as subtypes of protocols

### PR DESCRIPTION
**Pull request by ilevkivskyi**
See https://github.com/python/mypy/issues/5018 for motivation.

Attn: @gvanrossum @JukkaL @ambv

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
See https://github.com/python/mypy/issues/5322

**Comment by gvanrossum** [comment]
Whoa. If you don't feel like working on this, fine, but there's no need to close the PR.

**Comment by brettcannon** [comment]
I tweaked the title to say "WIP" so people know it's still open on purpose.

**Comment by ilevkivskyi** [comment]
As we discussed recently, there is no need to wait for full implementation before acceptance (this part of the PEP is not implemented in mypy). I looked at this again, and seems to me this can be merged as is, the current proposal matches the discussion in https://github.com/python/mypy/issues/5322.

**Pull request merged**
