### PR TITLE
Pep 508 parser fixes

### PR DESCRIPTION
**Pull request by michaelplaing**
Fix 1 bug. Enhance handling of trailing whitespace for URLs. Correct spelling.

Add tests.

### CODE REVIEW

**Comment by gvanrossum** [comment]
@dstufft Can you review this? Or @rbtcollins ?

**Comment by rbtcollins** [comment]
This looks fine to me. I haven't actually followed the reviewer process for us on github yet, so I'm hesitant about hitting the merge button - but the change is good.

**Comment by gvanrossum** [comment]
The review process for PEPs is pretty casual, the key points are (a) always Squash Merge, (b) make up a decent commit message (the GitHub default for Squash Merge is lame if there were multiple commits originally). I've done it for you.

**Comment by rbtcollins** [comment]
Thanks!

**Pull request merged**
