### PR TITLE
reSTify PEP225, PEP234, PEP255, PEP450

### PR DESCRIPTION
**Pull request by csabella**
For #4.

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
Would be better to avoid reflowing lines. This would make reviewing easier.

**Comment by csabella** [comment]
@serhiy-storchaka   Sorry, I thought one of the steps in converting to reST was to make the lines fit close to 79 characters.  Should I not do that?

**Comment by brettcannon** [comment]
@csabella I think @serhiy-storchaka makes an interesting point of reviewability. I say don't worry about reflowing since almost everyone views the PEPs as rendered HTML anyway.

**Comment by brettcannon** [comment]
Thanks!

**Pull request merged**
