### PR TITLE
Revert "PEP 517: add missing def for the mandatory hook build_wheel signature"

### PR DESCRIPTION
**Pull request by apidwalinsubport**
Reverts python/peps#2535

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
This appears to another spammer or bot, FYI—this PR has no plausible logical reason to revert the commit (which is easy for a bot or unskilled human to mass-spam), its a nearly brand new account, very high rate of contributions, contributions seemingly random or purely for inflating its numbers, with no logic to them, and mostly on its own repositories, just like the others we've seen.

@python/organization-owners :point_up:

**Comment by Rosuav** [comment]
Huh. The bot says that all commit authors have signed the CLA. So either the spammer is registered as having signed, or a reversion is listed differently from a regular commit.

**Comment by ambv** [comment]
Well, spammers are also able to sign CLAs. This is what happened in this case.

**Comment by CAM-Gerlach** [comment]
Yeah, I anecdotally suspect based on the fact they've shown just enough minimal interaction and variety elsewhere that it is probably a human spammer, rather than just a bot. Or if it is, they've gotten a good deal better...

**Pull request closed without merging**
