### PR TITLE
PEP 616: Mark as Final

### PR DESCRIPTION
**Pull request by gustavgransbo**
This resolves #2868.

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]

**Review by AA-Turner — APPROVED** [review]

**Comment by AA-Turner** [comment]
Impressively, merging this managed to create an empty commit -- some sort of race condition in GitHub's logic perhaps? 

The offending commit: https://github.com/python/peps/commit/5e6cef777696de43fdb33cd34557f8fb02d9a8a6

A

**Comment by CAM-Gerlach** [comment]
Never seen that happen before—I've reported it. Seems this is also missing a Resolution header, as many PEPs are.

**Comment by JelleZijlstra** [comment]
@AA-Turner it's probably fine but I'd have waited for a few days to give the PEP owner a chance to say that we should wait. Some PEPs may have rough corners that aren't immediately apparent and that still need to be finalized. No need to revert though, unless the PEP owner actually asks for it.

**Comment by AA-Turner** [comment]
Ahh, I got slightly mixed up and thought Eric was the author of 616, rather than the sponsor -- thank you for the note!

A

**Comment by AA-Turner** [comment]
> Seems this is also missing a Resolution header

https://mail.python.org/archives/list/python-dev@python.org/thread/2VGR3BMACYLARB7SKGX3SDPPXIXZSJE2/

A

**Pull request merged**
