### PR TITLE
Convert PEP 202 to reST

### PR DESCRIPTION
**Pull request by Mariatta**
as per #4 
Let me know if this works.
Thanks 😃

### CODE REVIEW

**Comment by gvanrossum** [comment]
Let's see if this shows up right on the website! Give it a few minutes.

**Comment by gvanrossum** [comment]
Whee!

**Comment by Mariatta** [comment]
:tada: Thanks so much, Guido! :smile:

**Comment by gvanrossum** [comment]
Did you write a script to do this or did you do this one by hand?

**Comment by Mariatta** [comment]
I did it the low-tech way (manual conversion) :sweat_smile: 
Let me see what I can do about writing a conversion script :thinking: 
PEP 3144 can be a good test case https://www.python.org/dev/peps/pep-3144/
What do you think?

**Comment by brettcannon** [comment]
I think PEP 3144 seems reasonable.

**Comment by gvanrossum** [comment]
+1. I'd be happy to review!

**Pull request merged**
