### PR TITLE
PEP 458: add note about compressing metadata

### PR DESCRIPTION
**Pull request by trishankatdatadog**
Add note about compressing metadata per @ewdurbin feedback

### CODE REVIEW

**Comment by ewdurbin** [comment]
In discussion I referenced this sentence from the very last part of the "Metadata Scalability" section, which also discusses JSON metadata. I'm not sure if it should be duplicated in both places.

**Comment by trishankatdatadog** [comment]
Oh, doh, I didn't realize! Let me just close this then?

**Comment by ewdurbin** [comment]
I think so, I'm not sure which section it fits best in though.

**Comment by trishankatdatadog** [comment]
I think where it is works best

**Pull request closed without merging**
