### PR TITLE
PEP 637 Removes contribute from other author

### PR DESCRIPTION
**Pull request by stefanoborini**

### CODE REVIEW

**Comment by Rosuav** [comment]
I feel a bit out of the loop here, what's up?

**Comment by stefanoborini** [comment]
Alternative PR as from author request

https://github.com/python/peps/pull/1648

Either of the two has to be merged after his approval.

**Comment by stefanoborini** [comment]
Closing. https://github.com/python/peps/pull/1648 replaces this PR.

**Comment by quechi199900** [comment]
2020-10-12 2:33 GMT+07:00, Stefano Borini <notifications@github.com>:

**Comment by quechi199900** [comment]
2020-10-12 2:39 GMT+07:00, BOSS QRT <quechi199917@gmail.com>:

**Pull request closed without merging**
