### PR TITLE
Cosmetic edits.

### PR DESCRIPTION
**Pull request by domnikkk**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by Mariatta** [comment]
This seems like an invalid PR. 
@bitdancer, you created the `cosmetic_edits_pep552` branch but didn't create any pull request.
Is the branch still needed?

**Comment by bitdancer** [comment]
I did create a PR.  Benjamin made it obsolete before he noticed that it existed.  I assumed he closed the PR and deleted the branch, but I didn't check.  The branch can certainly be deleted.

**Comment by Mariatta** [comment]
I see. Ok thanks :) I'm closing this PR and will delete the branch.

**Pull request closed without merging**
