### PR TITLE
PEP 654: reference 12029 re: using the same check as except for a match

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by gvanrossum** [comment]
I'm going to leave it up to @iritkatriel and/or @1st1 to approve this addition -- I'm not sure this issue is relevant for the readers of the PEP (although it is the reason of this particular phrasing).

**Comment by iritkatriel** [comment]
If anything, shouldn't we reference the language reference?  
https://docs.python.org/dev/reference/compound_stmts.html#the-try-statement

**Comment by gvanrossum** [comment]
I don't think we need to point to the language reference -- it's implied.
:-)

**Comment by 1st1** [comment]
I'm not sure I see the point of linking that issue. Perhaps @graingert could explain?

**Pull request closed without merging**
