### PR TITLE
PEP 584: Fix examples from likely copy-paste bug

### PR DESCRIPTION
**Pull request by EmilStenstrom**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by EmilStenstrom** [comment]
CLA has been signed, just waiting for the document to be accepted on your side.

**Comment by stevendaprano** [comment]
Sorry guys, I'm still having technology difficulties that make it hard 
for me to interact with Github's website.

It does look like a copy-paste error to me, but the suggested correction 
isn't quite right since d has already been modified in place. The 
previous call to print(d) gives

{'spam': 1, 'eggs': 2}

so the 'cheese' key has been removed. After ``d -= {'spam', 'parrot'}`` 
we should have

{'eggs': 2}

and the second example ``d -= [('spam', 999)]`` needs to be deleted in 
full. To be clear, here's the relevant section in full:

# --- cut here %< ---

Dict difference ``-`` will return a new dict containing the items from 
the left operand which are not in the right operand.

    >>> d = {'spam': 1, 'eggs': 2, 'cheese': 3}
    >>> e = {'cheese': 'cheddar', 'aardvark': 'Ethel'}
    >>> d - e
    {'spam': 1, 'eggs': 2}
    >>> e - d
    {'aardvark': 'Ethel'}

Augmented assignment will operate in place.

    >>> d -= e
    >>> print(d)
    {'spam': 1, 'eggs': 2}


Like the merge operator and list concatenation, the difference operator 
requires both operands to be dicts, while the augmented version allows 
any iterable of keys.

    >>> d - {'spam', 'parrot'}
    Traceback (most recent call last):
      ...
    TypeError: cannot take the difference of dict and set

    >>> d -= {'spam', 'parrot'}
    >>> print(d)
    {'eggs': 2}


# --- cut here %< ---



-- 
Steven

**Comment by gvanrossum** [comment]
OK, I'll send a new PR and you can approve that. Thanks @EmilStenstrom for noticing something was wrong here!

**Comment by EmilStenstrom** [comment]
Oh, I read the three examples to be independent, so that you could compare two different ways of doing the same thing. Happy to see it fixed!

**Pull request closed without merging**
