### PR TITLE
[WIP] PEP 452: Update hash algorithm PEP

### PR DESCRIPTION
**Pull request by tiran**
Work in progress, I'll add rational for new stuff later.

Signed-off-by: Christian Heimes <christian@python.org>

### CODE REVIEW

**Comment by gvanrossum** [comment]
@tiran Should this be merged? Or are you just using this PR as a holding area? (I'd actually prefer it if people didn't do that -- ideally you have a fork of the peps repo where you do your work and you submit a PR only when you're ready for it to be merged. Otherwise you invite people to start commenting on the PR, which doesn't seem a great workflow, and not one encouraged by PEP 1.)

**Comment by vstinner** [comment]
@tiran @stratakis: What's the status of this PEP update?

**Comment by stratakis** [comment]
The PEP has been marked as final at fcb7ffe. What are the next steps here?

**Comment by tiran** [comment]
@vstinner, @stratakis 

@brettcannon and I agreed that it's best to finalize PEP 452 and create a new PEP for improvements. The old PEP has been a defacto standard for many years. I'll discuss the matter at PyCon and open a new PEP afterwards.

**Comment by brettcannon** [comment]
@tiran what's the status of this PR?

**Comment by gvanrossum** [comment]
I'm just closing this -- @tiran hasn't responded to questions.

**Pull request closed without merging**
