### PR TITLE
PEP 669: Update specification to return current callback object

### PR DESCRIPTION
**Pull request by markshannon**

### CODE REVIEW

**Comment by hugovk** [comment]
The RTD build preview failed because this branch is a long way behind `main` so it doesn't have the RTD config version to switch the build from default Python 3.7 to required 3.9.

A rebase would fix it, but I wouldn't worry for such a small PR. Recommended for future PRs though :)

**Review by JelleZijlstra — APPROVED** [review]

**Comment by markshannon** [comment]
@JelleZijlstra Does the `docs/readthedocs.org:pep-previews` failure matter?

**Comment by hugovk** [comment]
We now have these buttons:

image

See https://github.com/python/peps/issues/2495 for more.

I'll do an update with rebase.

**Comment by hugovk** [comment]
Or rather I won't as I see you just found it :)

**Comment by markshannon** [comment]
I don't like merging things with broken tests. Merging main is easy enough.

**Pull request merged**
