### PR TITLE
Cap Sphinx to 6.0.0

### PR DESCRIPTION
**Pull request by AA-Turner**

### CODE REVIEW

**Comment by AA-Turner** [comment]
Confirmed images are restored: https://pep-previews--2950.org.readthedocs.build/pep-0458/#signing-metadata-and-repository-management

**Comment by CAM-Gerlach** [comment]
To clarify for others, this is in reference to images not being copied on the CIs when Sphinx was upgraded from 6.0.0 -> 6.1.1 between jobs, as first discovered on #2949 and documented in https://github.com/python/peps/pull/2949#issuecomment-1373884471 .

The specific version causing the change appears to be 6.1.0; 6.0.1 copies the images https://github.com/CAM-Gerlach/peps/actions/runs/3857659590/jobs/6575295318 whereas 6.1.0 does not https://github.com/CAM-Gerlach/peps/actions/runs/3857683684/jobs/6575346593 with all else held constant.

However, I cannot reproduce the issue locally on my Windows machine to be able to `git bisect` even with identical versions of everything, and my Linux boxes/VMs don't have a recent enough Python version installed by default. As @hugovk can repro it on his Mac, it seems to be a *nix-specific issue.

**Comment by hugovk** [comment]
```
b32841e153431ec02de31e9ec32e79ab3ac7d1c2 is the first bad commit
commit b32841e153431ec02de31e9ec32e79ab3ac7d1c2
Author: Adam Turner <9087854+aa-turner@users.noreply.github.com>
Date:   Mon Jan 2 15:02:33 2023 +0000

    Move tasks into parallel writing

 sphinx/builders/html/__init__.py | 17 ++++++++---------
 1 file changed, 8 insertions(+), 9 deletions(-)
```

https://github.com/sphinx-doc/sphinx/commit/b32841e153431ec02de31e9ec32e79ab3ac7d1c2

**Comment by AA-Turner** [comment]
https://github.com/sphinx-doc/sphinx/pull/11100 has an attempt at a fix.

A

**Comment by hugovk** [comment]
https://github.com/sphinx-doc/sphinx/pull/11100 fixes it locally for me, thanks!

**Pull request merged**
