### PR TITLE
Prohibit type variables inside ClassVar

### PR DESCRIPTION
**Pull request by pkch**
Fixes https://github.com/python/peps/pull/239#issuecomment-301079259.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
You mean ClassVar, not TypeVar (I was confused).

**Comment by pkch** [comment]
Actually I wouldn't be surprised if there's no explicit language prohibiting them inside `TypeVar` either :)

**Comment by ilevkivskyi** [comment]
@pkch Thanks, LGTM!

**Comment by ilevkivskyi** [comment]
I think this is ready. Could someone with write access please merge this PR?

**Comment by Rosuav** [comment]
Done.

**Comment by ilevkivskyi** [comment]
@Rosuav Thank you!

**Pull request merged**
