### PR TITLE
PEP 567: avoid _NO_DEFAULT, use [default] syntax

### PR DESCRIPTION
**Pull request by vstinner**
Replace ContextVar(name, *, default=_NO_DEFAULT) with ContextVar(name, *, [default]).

### CODE REVIEW

**Comment by vstinner** [comment]
cc @1st1 @gvanrossum

**Comment by 1st1** [comment]
I like this change, Guido, what do you think?

**Comment by vstinner** [comment]
Other examples of [optional_parameter] syntax:

* https://docs.python.org/dev/library/os.html#os.sendfile
* https://docs.python.org/dev/library/functions.html#breakpoint (bytearray, bytes)
* https://docs.python.org/dev/library/functions.html#format
* etc.

I'm not sure if we already have examples of keyword-only optional parameters written with [arg] syntax in the doc.

**Comment by gvanrossum** [comment]
I don't like the `ContextVar(name, *, [default])` case -- it suggests you can write `ContextVar('foo', 42)`. Let's leave well enough alone. This is a PEP, not end user docs.

**Comment by vstinner** [comment]
Aha, I found another example of optional keyword-only parameters:

```
max(iterable, *[, key, default])
```

https://docs.python.org/dev/library/functions.html#max

Builtin help():

```
vstinner@apu$ ./python
Python 3.7.0a4+ (heads/master-dirty:44a70e9336, Jan 17 2018, 15:40:30) 
>>> help(max)
Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.
```

**Comment by gvanrossum** [comment]
I still don't like it for the PEP. Please let it go.

**Comment by vstinner** [comment]
> I still don't like it for the PEP. Please let it go.

Don't worry, it just was a proposal. I'm fine to keep the current syntax :-)

I just wanted my PR to be complete ;-)

**Pull request closed without merging**
