### PR TITLE
PEP 13: Update the most-recent-election PEP reference to PEP-8101

### PR DESCRIPTION
**Pull request by bskinn**

### CODE REVIEW

**Comment by bskinn** [comment]
&lt;chuckle&gt; Sorry if I should've taken this through other channels first! Seemed pretty uncontroversial. 🙂

**Comment by warsaw** [comment]
You're good @bskinn - thanks for the contribution!  

Does @brettcannon @vstinner @willingc or @Yhg1s have any objections to just merging this typo fix?

**Comment by Yhg1s** [comment]
No, this is clearly the intent of the original change.

**Comment by vstinner** [comment]
Would it make sense to track all past councils as well in the PEP 13, not only the current one?

**Comment by bskinn** [comment]
The same thing occurred to me, @vstinner. I didn't put it in this PR since it'd be a much more substantial change.

Alternatively, perhaps a new meta-PEP, e.g., "History of Steering Council Elections," would be good? It would reduce clutter in PEP 13.

**Comment by vstinner** [comment]
> Alternatively, perhaps a new meta-PEP, e.g., "History of Steering Council Elections," would be good? It would reduce clutter in PEP 13.

We have PEP 13, PEP 8000 + PEP 8001 .. PEP 8016, PEP 8100 and 8101: a total of 20 PEPs. I am not sure that yet another PEP would help to make the overall set of PEPs more consistent :-)

Documenting past councils should take too many space in the PEP 13, we can just point to PEP 81xx PEPs:

* PEP 8101 -- 2020 Term steering council election
* PEP 8100 -- January 2019 steering council election

**Comment by vstinner** [comment]
> Does @brettcannon @vstinner @willingc or @Yhg1s have any objections to just merging this typo fix?

This PR doesn't change the governance, just enhance the document itself. No need to vote for that ;-)

**Comment by pradyunsg** [comment]
> Documenting past councils should take too many space in the PEP 13, we can just point to PEP 81xx PEPs:

Did you mean "should not"?

**Comment by bskinn** [comment]
@vstinner Ah, sure, just a bulleted list of PEP links, that'll be concise. I'd thought you meant including the full list of Council members for each election in PEP 13 itself.

**Comment by vstinner** [comment]
> Did you mean "should not"?

Right :-)

**Comment by warsaw** [comment]
Thanks for weighing in everyone.  Since this is not a substantive change to governance, it doesn't need a vote.  I've gone ahead and merged this change.  I think we're also fine on the current suite of PEPs, but if someone feels differently, feel free to propose separate changes.

**Pull request merged**
