### PR TITLE
PEP 671: Add Discussions-To header

### PR DESCRIPTION
**Pull request by davidfstr**
I've linked what appears to be the latest discussion thread for this PEP.

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
Thanks! If you're going to update the Discussions-To, could you update the `Post-History` as well?

```rst
Post-History: 24-Oct-2021, `01-Dec-2021 <https://mail.python.org/archives/list/python-ideas@python.org/thread/UVOQEK7IRFSCBOH734T5GFJOEJXFCR6A/>`__
```

**Review by CAM-Gerlach — APPROVED** [review]
LGTM, thanks! @Rosuav ?

**Review by raghavthind2005 — APPROVED** [review]

**Comment by davidfstr** [comment]
@Rosuav, does this small revision to the headers of PEP 671 look okay to you?

**Review by Rosuav — APPROVED** [review]

**Comment by Rosuav** [comment]
Oops! I was sure that I'd pushed the button to say "yes, I approve of these changes", but something didn't happen. Not sure. Assume that I messed up somewhere in the UI, tha's the most likely cause. Yes, that looks fine, and I *think* this time that I've submitted an approving review.

**Review by JelleZijlstra — APPROVED** [review]

**Pull request merged**
