### PR TITLE
Update outdated links in PEP 3107 with archived pages

### PR DESCRIPTION
**Pull request by Mariatta**
Fixes https://github.com/python/peps/issues/168

### CODE REVIEW

**Comment by Rosuav** [comment]
Good point. If it dies, people can come look through the git/hg history to find the actual URL - won't be too hard.

:+1:

**Comment by brettcannon** [comment]
Thanks!

**Comment by gvanrossum** [comment]
Actually I would have recommend using www.archive.org which *is* a
respected site (assuming it does have the desired pages archived).

**Comment by Mariatta** [comment]
😞 :woman_facepalming: Eh .... so ...  maybe earlier I wasn't trying hard enough to look for the archived version for the first link on archive.org 😓  🙇‍♀️ 
sorry for that 😅 
I found it now 🎉 
http://web.archive.org/web/20070730120117/http://oakwinter.com/code/typecheck/

fixed in https://github.com/python/peps/pull/170

**Pull request merged**
