### PR TITLE
Update 469, 464, 470 to Final

### PR DESCRIPTION
**Pull request by brainwane**
@dstufft this is per our conversation on Friday. Will you double-check that the Resolutions and Statuses on these are appropriate?

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by brainwane** [comment]
(I just signed the CLA, so the bot will think I haven't done so yet.)

**Comment by brainwane** [comment]
Still waiting for my bugs.python.org personal details page to mention that my contributor agreement form has been received. Not sure whether I should follow up directly with Ewa or do something else to check.

**Comment by brettcannon** [comment]
@brainwane if it has not been flipped then Ewa is probably just swamped with PyCon (she's the one that does the actual toggle on the field).

**Comment by brettcannon** [comment]
But since Donald approved the changes and they are not exactly semantic stuff I have gone ahead and merged this.

**Pull request merged**
