### PR TITLE
Use number 9999 in a draft PEP

### PR DESCRIPTION
**Pull request by Mariatta**
Update PEP 1 and PEP 12 with instruction to use the number 9999.

Closes https://github.com/python/peps/issues/223

### CODE REVIEW

**Comment by brettcannon** [comment]
I like it, but maybe @warsaw has an opinion?

**Comment by brettcannon** [comment]
Do any @python/pep-editors have an opinion on this? I say we make the change.

**Comment by Rosuav** [comment]
I'm in favour.

**Comment by Mariatta** [comment]
🤔 Do I need to email python-dev about this change?

**Comment by brettcannon** [comment]
OK, I say merge this and a quick note to python-dev would be good.

**Pull request merged**
