### PR TITLE
PEP 681: Fix minor formatting and typographical issues

### PR DESCRIPTION
**Pull request by davidfstr**
Please see individual commit messages for explanation of each change made.

### CODE REVIEW

**Comment by davidfstr** [comment]
CC @debonte (PEP Author)

**Comment by hugovk** [comment]
https://github.com/python/peps/pull/2382/commits/2e8212bb57d4c76c97eac6513e1524a2bb432a71:

> * I believe '''-style headers are also recommended by the PEP rST template
  for this level of header, but I haven't confirmed.

Correct! 👍 

```rst
First-Level Title
=================

Second-Level Title
------------------

Third-Level Title
''''''''''''''''' 
```

https://python.github.io/peps/pep-0012/#section-headings

**Review by JelleZijlstra — APPROVED** [review]

**Review by CAM-Gerlach — COMMENTED** [review]
LGTM, thanks! Some clarifications:

> [Nit: Adjust PEP reference to include the word "PEP"](https://github.com/python/peps/pull/2382/commits/d0ab16a4e455ccb629d3db2f6b74dab73c98688c)

Just to make sure we're clear, this is only needed for PEPs that have custom inline link text, which by extension includes those linking to sections (as here). For "normal" `` :pep:`1` `` links, "PEP" is prepended automatically as part of the generated inline link text.

> [Remove gremlin character <0x0c>](https://github.com/python/peps/pull/2382/commits/83b4d2de9bec29603691359f850603da7924d804)

The `FF` (form feed) character is needed for Emacs to recognize the Emacs editor configuration block that follows it at the end of the file. Previously, this was required and included in all PEPs, but as it is effectively obsolete (given only a few PEP editors/authors still use Emacs, and those that do pretty much all use `rst-mode` which renders this unnecessary) this requirement was removed in #2374 .

Without the `FF` character the following block is (AFAIK) useless, so if you eliminate that, the Emacs config comment following it should be removed as well, or otherwise both should be left alone (and the commit dropped).

**Comment by debonte** [comment]
@davidfstr, based on https://github.com/python/peps/pull/2374 and @CAM-Gerlach's comment above, I'd say we should remove the Emacs configuration block at the end of the file.

Thanks for these changes!

**Review by AA-Turner — APPROVED** [review]

**Comment by davidfstr** [comment]
I believe all feedback has been integrated and this PR is ready to merge. 👍

**Pull request merged**
