### PR TITLE
PEP 639: Changes for clarity and consistency

### PR DESCRIPTION
**Pull request by kpfleming**
Various changes to improve clarity and consistency. None of the changes
should change the meaning of any content.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@kpfleming

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by kpfleming** [comment]
Odd, I signed the CLA on January 23; I'm guessing it hasn't appeared in the database yet since all the days between that day and today were weekend days :-)

**Review by pombredanne — APPROVED** [review]
@kpfleming Looking good! Thank you ++

**Comment by brettcannon** [comment]
@kpfleming your CLA is still not showing up; what is your bugs.python.org account name?

**Comment by kpfleming** [comment]
That is also 'kpfleming'.

**Comment by brettcannon** [comment]
@kpfleming it hasn't been recorded yet. Can you email contributors@python.org to see what's happened to your CLA?

**Comment by kpfleming** [comment]
Done, I forwarded a copy of the signed document I received from AdobeSign as well.

**Comment by kpfleming** [comment]
Betsy has confirmed that the Contributor Agreement has been recorded now, and I see it in my profile in BPO.

**Comment by brettcannon** [comment]
@kpfleming thanks!

**Pull request merged**
