### PR TITLE
[WIP] Rename rst peps to `.rst`

### PR DESCRIPTION
**Pull request by Carreau**
Not sure how many things that would break when pushing on pythondotorg. That's pretty easy to redo if it's not the right time.

### CODE REVIEW

**Comment by berkerpeksag** [comment]
Thanks! Yes, this will definitely break python.org :) I have a WIP branch that fixes a couple issues with the PEP importer. I can tweak it look for `.rst` files too but I'm not sure I can get to it this week.

**Comment by brettcannon** [comment]
I've marked this PR as a work-in-progress until the python.org  side is dealt with.

**Comment by Carreau** [comment]
> I've marked this PR as a work-in-progress until the python.org side is dealt with.

Sure, if you want a cleaner PR queue, feel free to close, we can reopen when time is right.
It's easy to redo.

**Comment by brettcannon** [comment]
Is there an issue or PR for the pydotorg side of things that we can track in regards to this PR?

**Comment by berkerpeksag** [comment]
No, I was planning to fix it (also hg.python.org links needs to be updated) while working on https://github.com/python/pythondotorg/issues/825 :)

**Comment by abalkin** [comment]
Note that PEP preambles are not in valid reST format.  Would it break PEP processing tools if they are converted to reST comments (.. directive) or pre-formatted text (:: directive)?

**Comment by brettcannon** [comment]
@abalkin yes, they would break. Eventually the headers would need to be changed to be valid reST, but one thing at a time. 😄

**Comment by Carreau** [comment]
Closing to keep things clean, it's easy to redo.

**Pull request closed without merging**
