### PR TITLE
pep-0622.rst: fix typo

### PR DESCRIPTION
**Pull request by Delta456**
PEP 622: Summary of the changes made

Change `patten` to `pattern`

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@Delta456

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by Delta456** [comment]
It will take me time to make an ID till then you guys will have to wait.

**Comment by Delta456** [comment]
eh ok

**Comment by Delta456** [comment]
I am signed the CLA but it isn't showing it.

image

**Comment by brandtbucher** [comment]
It takes a business day or two. Not a big deal since this is such a simple fix.

**Comment by Delta456** [comment]
Oh ok! Glad to be working with you guys though!

**Comment by brandtbucher** [comment]
Glad to have you.

**Pull request merged**
