### PR TITLE
PEP 287: fix typo in word frangible

### PR DESCRIPTION
**Pull request by hexum**
Spelling `frungible` changed to `frangible`.

### CODE REVIEW

**Comment by hexum** [comment]
`Fungible` word could be meant here. It's not clean for me, but there is a mistake anyway.

**Comment by Rosuav** [comment]
Or was it intentionally a nonsense word? Is there any particular indication that the original author intended any given meaning?

**Comment by hexum** [comment]
May be.
It's not critical part of document. But readers like me stops and start trying to understand this strange word =)

**Comment by brettcannon** [comment]
Why don't we ask @goodger what he meant to write? (my suspicion is it was meant to be a nonsense word).

**Comment by goodger** [comment]
You are correct: it's just a nonsense word in an example.

DG

**Comment by hexum** [comment]
Thanks for your answers!
Next time I will not be too serious while reading peps =)

**Pull request closed without merging**
