### PR TITLE
Remove "XXX Mention docstrings of 2.2 properties."

### PR DESCRIPTION
**Pull request by jamesray1**
See https://github.com/python/peps/issues/484 for details.

Closes https://github.com/python/peps/issues/484

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by brettcannon** [comment]
Thanks, @jamesray1 . I'm ignoring the lack of CLA since this is a trivial change, but do please consider signing the CLA to make future contributions easier to review/consider.

**Comment by jamesray1** [comment]
Hi @brettcannon, I did try to follow the steps given by the bot but I was not able to complete my registration with the Python tracker. It has been notified.

**Comment by brettcannon** [comment]
@jamesray1 That's fine as there's a human component to the registration that adds a day to the processing time. My comment was more of a "just in case" thing. :)

**Pull request merged**
