### PR TITLE
Add Adam Turner as the default reviewer for PEP infrastructure

### PR DESCRIPTION
**Pull request by AA-Turner**
I'll regret this!
A

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]
Thank you!

**Comment by AA-Turner** [comment]
First PR merged, too! 🎉

**Comment by CAM-Gerlach** [comment]
Great! A few other things you might want to considering also claiming, in case you haven't:

* `/docs` (co-claim with me, if desired; at least until we decide what to do with them)
* `/.github/workflows` (I can co-claim as well)
* `Makefile` (since your work has considerable effect on this)
* `requirements.txt` (you'll likely want to know when deps are changed)

I will propose to claim `.pre-commit-config.yml`, since I wrote most of it in its current form (along with Hugo) and I'm pretty intimately familiar with pre-commit.

**Comment by AA-Turner** [comment]
Done apart from `/docs` (in case we remove all docs, don't want needless churn)
A

**Comment by CAM-Gerlach** [comment]
Thanks!

**Pull request merged**
