### PR TITLE
Fix typo: Set -> set

### PR DESCRIPTION
**Pull request by martinbroadhurst**

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by Rosuav** [comment]
This is a trivial change (I can't see any reason for this to be a specialized class here), so I'm going to override the bot. I recommend checking the CLA requirements for next time, though, as it'll smooth things out. Thanks for fixing this!

**Comment by bitdancer** [comment]
This was not a typo, and so I don't think this should have been merged.  At the time that pep was written, Set was the correct spelling.  'set' did not get added to the language until python 2.4, the same version in which this PEP landed.  However, now that it is merged it is not also not worth reverting, since both peps did both land in 2.4, and the distinction is now of only historical interest.  (But don't forget that most PEPs are historical documents :)

**Comment by Rosuav** [comment]
Ah, I'm sorry, I was looking through for a reason for that and missed seeing the version. My bad! Sorry.

**Comment by bitdancer** [comment]
Well, those of us who have been doing this long enough that we *remember* when set was Set have a bit of an advantage in spotting such a thing :)

**Comment by Rosuav** [comment]
Haha, yeah. I was thinking "this proves how big a noob I am", given that I didn't seriously start using Python until about 2.6. And then I talk to JavaScript people and realise that I've been using Python for longer than Node.js has been around. Noob? Old hand? It's all relative...

**Pull request merged**
