### PR TITLE
Update PEP 487

### PR DESCRIPTION
**Pull request by tecki**
This adds the changes proposed by Guido at 
https://mail.python.org/pipermail/python-dev/2016-July/145606.html

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

Unfortunately we couldn't find an account corresponding to your GitHub username at [bugs.python.org](http://bugs.python.org/) (b.p.o). If you don't already have an account at b.p.o, please [create one](http://bugs.python.org/user?@template=register) and make sure to add your GitHub username. If you do already have an account at b.p.o then please go there and under "Your Details" add your GitHub username.

And in case you haven't already, please make sure to sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA); we can't legally look at your contribution until you have signed the CLA.

Once you have done everything that's needed, please reply here and someone will verify everything is in order.

**Comment by tecki** [comment]
Hi,

I just added my github name, please update the markers there.

Greetings

Martin
Am 14.07.2016 11:28 AM schrieb "the-knights-who-say-ni" <
notifications@github.com>:

**Comment by tecki** [comment]
Not sure whether I am supposed to respond here, but I just added my github name on b.p.o, hopefully that's enough shrubbery.

**Comment by berkerpeksag** [comment]
Thanks!

**Pull request merged**
