### PR TITLE
enable netlify

### PR DESCRIPTION
**Pull request by ewdurbin**

### CODE REVIEW

**Comment by ewdurbin** [comment]
Not sure what's up... seems it might be an incompatibility with python3.8 (best available on netlify)

**Comment by AA-Turner** [comment]
I don't think PEPs need Netlify, as we already have render previews. Is there a reference to the discussion for this at all?

A

**Comment by ewdurbin** [comment]
wires crossed here, I read that as CAM asking for netlify here https://github.com/python/peps/pull/2875#pullrequestreview-1172967034

**Comment by AA-Turner** [comment]
No worries, thank you--good that the CPython previews are now enabled.

A

**Comment by CAM-Gerlach** [comment]
Sorry for the confusion, and thanks for taking care of that—it will be a huge benefit there to both PR authors and reviewers alike!

**Pull request closed without merging**
