### PR TITLE
Add PEP 538 to 3.7 release schedule

### PR DESCRIPTION
**Pull request by chicheng**
Fix 3.7 release schedule version number typo

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by chicheng** [comment]
CLA signed. Will @the-knights-who-say-ni refresh the status automatically?

**Comment by brettcannon** [comment]
@chicheng it will refresh if you push a change or a core dev removes the label (like I just did 😄 ).

**Comment by ned-deily** [comment]
Thanks for you contribution, @chicheng!

**Pull request merged**
