### PR TITLE
Update pep-0282.txt

### PR DESCRIPTION
**Pull request by daxm**
Modify mymodule.py, myapp.py, and the resulting output to work with Python 3.6.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again to your contribution and we look forward to looking at it!

**Comment by daxm** [comment]
I've signed the CLA but my account appears broken.  Even though I verified my email address my login only gives "Invalid Login" error message when I attempt to log in.

**Comment by JelleZijlstra** [comment]
Final PEPs are a historical record; I don't think we should update their syntax.

**Comment by daxm** [comment]
Then I'd suggest that we do one of the following:
1.  Document the fact that the example shown only works in Python 2.
2.  Add a new example that is Python 3 compliant.
3.  Delete the example.

Personally I don't like any of these options.  It would be my preference to upkeep the PEP documentation to what is useful for the current needs of Python.  What is the use of an example if it no longer works?  What is the use of having a "historical" example, especially when people are looking to this documentation in an effort to learn how this feature works?

**Comment by pfmoore** [comment]
The Python documentation should have sufficient information - if it doesn't, then that's where changes should be made to ensure that people wanting to use the feature don't *need* to refer to the PEP.

**Comment by brettcannon** [comment]
If someone wants to leave a comment saying that the PEP is now for historical record and the documentation should be referred to how things work then that's fine, but updating the PEP's examples isn't necessary and worth trying to keep up-to-date.

**Pull request closed without merging**
