### PR TITLE
PEP 686: Postpone target version to 3.15

### PR DESCRIPTION
**Pull request by methane**
This change is based on SC feedback.
https://github.com/python/steering-council/issues/118#issuecomment-1108833536

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]

**Comment by methane** [comment]
May I update the status to "Accepted" in this PR too?

**Review by CAM-Gerlach — COMMENTED** [review]
LGTM

You could, but I suggest waiting until a formal acceptance message is posted to Python-Dev, it can be updated at the same time `Resolution` is added.

Really sorry for the long delay on the final proofreading pass; I've been busy getting ready for PyCon and taking care of some other things. Can I still go ahead with it (subject to your review, of course, and I'd be careful to not change anything substantive)?

**Comment by methane** [comment]
> Really sorry for the long delay on the final proofreading pass; I've been busy getting ready for PyCon and taking care of some other things. Can I still go ahead with it (subject to your review, of course, and I'd be careful to not change anything substantive)?

Never mind. And yes, please review this PEP when you have time.
I always use broken English so getting review about English is rare chance to improve my writing skill.

**Comment by CAM-Gerlach** [comment]
I wish I was a tenth as much an expert at the Python language, as you, Inada-san—I'd take that over writing perfect English any day. That's what we're here for, and its particularly great that its a good a learning opportunity; feel free to ask if you aren't sure about anything! And in fact, I have you to thank for my initial involvement in the PEPs repo, since the very first PEP I ever helped edit was your PEP 597, and its associated documentation/UI text in CPython.

**Pull request merged**
