### PR TITLE
PEP 614: Relaxing Grammar Restrictions On Decorators

### PR DESCRIPTION
**Pull request by brandtbucher**
Here's a first draft. Thanks @gvanrossum for sponsoring.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Make it PEP 614 and I’ll merge it.

**Comment by brandtbucher** [comment]
CI failure looks like a fluke. Closing and reopening to rebuild.

**Comment by brandtbucher** [comment]
Hm, the 3.7-dev build looks like an error on Travis's end (maybe a bad virtualenv activation):

```
$ pip --version
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7-dev/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
$ pip install docutils
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7-dev/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
```

The 3.7 build is okay, though.

**Comment by gvanrossum** [comment]
Ignoring the test failure, landing.

**Pull request merged**
