### PR TITLE
PEP 586: typo (MAy -> May)

### PR DESCRIPTION
**Pull request by vpoulailleau**
CLA is signed, but not yet confirmed, probably tomorrow.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by gvanrossum** [comment]
For such a one-bit change I don't think we need the CLA. :-) Still, please sign it to make your future contributions smoother!

**Comment by vpoulailleau** [comment]
I do agree ;-)

I love Python, I know C pretty well, I haven't had time yet to look at CPython, but I would be very happy to help in the future.

**Comment by gvanrossum** [comment]
Please do! Have you looked at where to start with CPython contributions yet? (Hint: it's called "devguide". :-)

**Comment by vpoulailleau** [comment]
I scratched the surface of the devguide a few years ago. I hope I'll have free time soon (in a few weeks), I'll start reading the devguide ASAP.

At that time, I wanted to help on CPython, but the steps to get the first pull request seemed long, so I switched to help translating the official Python docs in French (that requires almost no setup).

**Pull request merged**
