### PR TITLE
PEP 686: gh-91156 is fixed

### PR DESCRIPTION
**Pull request by methane**

### CODE REVIEW

**Review by hugovk — APPROVED** [review]
Thanks!

Re: https://github.com/python/cpython/issues/91156

**Comment by methane** [comment]
@CAM-Gerlach Now this PEP is submitted to SC and I finished last planned changes.
May I ask your copyediting?

**Comment by CAM-Gerlach** [comment]
Hey, really sorry for the delay and lack of a quicker response—I'd taken a break from GitHub for a short while and am still trying to catch up on my ever growing backlog, and have had this prioritized near the top for the past several days but more urgent things keep coming up, sorry. Hopefully I'll finally get to it by tomorrow. Thanks for your patience!

**Comment by CAM-Gerlach** [comment]
Hi @methane , really sorry for the delay and lack of a quicker response—I'd taken a break from GitHub for a short while and am still trying to catch up on my ever growing backlog, and have had this prioritized near the top for the past several days but more urgent things keep coming up, sorry. Hopefully I'll finally get to it by tomorrow. Thanks for your patience!

**Pull request merged**
