### PR TITLE
Fix colour scheme toggling when switching from default dark mode

### PR DESCRIPTION
**Pull request by wookie184**
Closes #2487 

(Just signed the CLA so may not have gone through yet)

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@wookie184

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Review by CAM-Gerlach — DISMISSED** [review]
LGTM; @hugovk ?

**Comment by CAM-Gerlach** [comment]
Hmm, on FF on Windows, I did see a bit of flashing when testing, but I thought it was due to an occasional double-tap issue with the mouse I was using (which would produce the same effect), and I didn't see it after I switched to another. I tested it now in a private window with a known-good mouse and with dark theme as my browser default, and it displayed dark on first load, switched to white on click and back to black on another click, as it should. I did see what I think was one flash after a bunch of tries, but I couldn't reproduce it again.

**Comment by hugovk** [comment]
macOS Monterey 12.3:

Cannot reproduce with Firefox 98 or Safari 15.4 in private mode.

Can pretty consistently reproduce the third-click thing in Chrome 99, not fast clicks, and waiting for page to load first.

**Comment by hugovk** [comment]
Thanks! I can also repro in Chrome 99 on Android.

**Comment by wookie184** [comment]
I've pushed the change swapping around the first two lines in the `makeLight` function. Previously the `makeLight` function seemed to run fine and the `dark` stylesheet *was* given the `disabled` attribute, but Chrome didn't seem to render that change.

I don't know why this fix works, but it does seem to work consistently for me in Chrome, Firefox, and Edge on windows 11. I'll try it on Chrome and Firefox on android with the build preview now 😓

**Comment by wookie184** [comment]
Ok it seems that didn't work at all, no idea why it was working locally, back to the drawing board...

**Comment by hugovk** [comment]
Thanks! Looking good for me now with Chrome, Safari and Firefox, starting in light, dark or auto.

**Review by hugovk — APPROVED** [review]
Quick test with Chrome on Android good too, starting from dark mode.

**Review by raghavthind2005 — APPROVED** [review]

**Review by CAM-Gerlach — APPROVED** [review]
LGTM, seems to work for me as well on FF/Win (only browser I have installed here, after my copy of Chrome for testing broke and I'm not terribly inclined to spend my time trying to accommodate a browser engine monoculture again)

**Comment by hugovk** [comment]
Thank you for the fix! This will help avoid a little moment of confusion on first visit.

**Pull request merged**
